apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
  - protocol: TCP
    port: 4222
    targetPort: 4222
  - protocol: TCP
    port: 8222
    targetPort: 8222
