apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4222
        - containerPort: 8222
        resources:
          requests:
            cpu: "100m"     # Solicita 0.1 CPU
            memory: "50Mi"  # Solicita 50 MB de memoria
          limits:
            cpu: "200m"     # Máximo 0.2 CPU
            memory: "100Mi" # Máximo 100 MB de memoria
