apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms
  template:
    metadata:
      labels:
        app: ms
    spec:
      containers:
      - name: ms
        image: ms:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"     # Solicita 0.1 CPU
            memory: "50Mi"  # Solicita 50 MB de memoria
          limits:
            cpu: "200m"     # Máximo 0.2 CPU
            memory: "100Mi" # Máximo 100 MB de memoria
