apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms
  template:
    metadata:
      labels:
        app: ms
    spec:
      containers:
      - name: ms
        image: ms:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "10m"     # Solicita 0.1 CPU
            memory: "1Mi"  # Solicita 50 MB de memoria
          limits:
            cpu: "20m"     # Máximo 0.2 CPU
            memory: "2Mi" # Máximo 100 MB de memoria
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 2
