apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms
  template:
    metadata:
      labels:
        app: ms
    spec:
      containers:
      - name: ms
        image: ms:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
